### ISSUE TITLE
Minimal example of SinzLab use-case

### ISSUE THREAD

**Issue by mohammadbashiri** [sinzlab/nnfabrik#81]
Let us keep nnfabrik as generic as possible but also encourage unity of approach among neuroscience labs.

What needs to be done?
* new example of dataset, model, and trainer functions
* a new notebook of showing how to use the functions
* change of readme to point to this use-case which we would encourage computational neuroscience labs to follow

**Comment by ArneNx** [comment]
Will be mainly addressed in PR #98

**Comment by ArneNx** [comment]
Better version with docu will come with PR  #104
